INSERT INTO CINEMA(ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Major,15','Tarragona','Yelmo',43021);

INSERT INTO CINEMA(ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Brugent, 10','Tarragona','Cinesa',43001);

INSERT INTO CINEMA(ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Rambla Nova, 20','Tarragona','Ocine',43004);