INSERT INTO CINEMA(ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Major,15','Tarragona','Yelmo',43021);

INSERT INTO CINEMA(ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Brugent, 10','Tarragona','Cinesa',43001);

INSERT INTO CINEMA(ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Rambla Nova, 20','Tarragona','Ocine',43004);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 1',120,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES 
('Sala 2',100,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 3',80,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 1',150,2);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 2',120,2);

 INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 3',100,2);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 1',200,3);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 2',150,3);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 3',120,3);



