INSERT INTO CINEMA(ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Major,15','Tarragona','Yelmo',43021);

INSERT INTO CINEMA(ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Brugent, 10','Tarragona','Cinesa',43001);

INSERT INTO CINEMA(ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Rambla Nova, 20','Tarragona','Ocine',43004);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 4',50,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES 
('Sala 5',50,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 6',80,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 7',70,2);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 8',50,2);

 INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 9',70,2);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 10',10,3);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 11',15,3);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID)VALUES
 ('Sala 12',60,3);



